import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "Angular";

export const angularConcepts = buildTechConcepts(T, [
  { name: "components and templates", beginner: "@Component decorator; templateUrl/styleUrls.", intermediate: "OnPush change detection strategy.", advanced: "Standalone components reduce NgModule boilerplate.", mcq: builders.mcq(T, "angular", "Interpolation syntax?", ["{{ }}", "${ }", "<% %>"], "{{ }}", "Binds component property.") },
  { name: "dependency injection", beginner: "constructor(private svc: Service) injects.", intermediate: "providedIn root vs module providers.", advanced: "InjectionToken for config values.", scenario: builders.scenario(T, "di", "NullInjectorError in tests.", "TestBed.configureTestingModule providers.", "Mock dependencies.") },
  { name: "RxJS and Observables", beginner: "async pipe subscribes/unsubscribes in templates.", intermediate: "switchMap cancels stale HTTP requests.", advanced: "shareReplay for multicasting.", coding: builders.coding(T, "Search typeahead debounce?", "debounceTime + distinctUntilChanged + switchMap.", "Avoid race.", "", "—", "—") },
  { name: "routing and guards", beginner: "RouterModule routes path component.", intermediate: "canActivate auth guard returns boolean/UrlTree.", advanced: "Lazy loaded feature modules reduce initial bundle.", why: "SPA architecture." },
  { name: "forms reactive vs template", beginner: "FormControl FormGroup validators.", intermediate: "Custom validators cross-field.", advanced: "ControlValueAccessor for custom inputs.", debug: builders.debug(T, "forms", "Value not updating.", ["Forgot formControlName", "OnPush without markForCheck", "Disabled zone"], "Forgot formControlName", "Check FormGroup structure.") },
  { name: "services and HttpClient", beginner: "HttpClient get/post returns Observable.", intermediate: "Interceptors add auth headers globally.", advanced: "Retry/backoff for transient errors.", scenario: builders.scenario(T, "http", "401 on all API calls.", "Interceptor refresh token queue.", "Silent refresh pattern.") },
  { name: "change detection zones", beginner: "Default checks all components; OnPush checks on input changes.", intermediate: "NgZone.runOutsideAngular for third-party libs.", advanced: "Signals (Angular 16+) fine-grained updates.", why: "Performance interviews." },
  { name: "NgModules vs standalone", beginner: "declarations imports exports in @NgModule.", intermediate: "bootstrapApplication for standalone root.", advanced: "Gradual migration from modules.", bestPractice: { question: "When OnPush?", answer: "Presentational components with immutable inputs.", explanation: "Fewer CD cycles." } },
  { name: "testing Jasmine Karma", beginner: "TestBed creates component fixture.", intermediate: "HttpClientTestingModule mocks backend.", advanced: "Spectator/Jest migration trends.", coding: builders.coding(T, "Test component with @Input?", "Set fixture.componentRef.setInput in Angular 14+.", "Or parent test host.", "", "—", "—") },
  { name: "pipes and directives", beginner: "date pipe formats in template.", intermediate: "Pure vs impure pipes performance.", advanced: "Structural *ngIf *ngFor trackBy.", why: "Template mechanics." },
  { name: "state management NgRx", beginner: "Store actions reducers selectors.", intermediate: "Effects for side effects.", advanced: "ComponentStore for local feature state.", scenario: builders.scenario(T, "state", "Prop drilling hell.", "Feature store or signals service.", "Pick complexity fit.") },
  { name: "build and deployment", beginner: "ng build --configuration production.", intermediate: "AOT compilation catches template errors.", advanced: "Budgets fail CI on bundle regression.", why: "Release engineering." },
]);
