import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "AWS";

export const awsConcepts = buildTechConcepts(T, [
  { name: "IAM users roles policies", beginner: "Least privilege IAM policies; roles for services.", intermediate: "STS temporary credentials.", advanced: "Permission boundaries and SCPs in orgs.", mcq: builders.mcq(T, "iam", "EC2 app accessing S3 should use?", ["Access keys on disk", "IAM instance profile role", "Root keys"], "IAM instance profile role", "No long-lived keys.") },
  { name: "EC2 and Auto Scaling", beginner: "Launch templates; ASG scales on CPU/requests.", intermediate: "ALB health checks replace unhealthy instances.", advanced: "Mixed instances policy spot+on-demand.", scenario: builders.scenario(T, "ec2", "Traffic spike during sale.", "ASG scale out; ALB; cache; DB read replicas.", "Well-Architected.") },
  { name: "S3 storage classes", beginner: "S3 Standard; IA; Glacier for archives.", intermediate: "Lifecycle rules transition objects.", advanced: "Strong consistency; multipart upload large files.", coding: builders.coding(T, "Presigned URL use case?", "Temporary upload/download without public bucket.", "Time-limited signature.", "", "—", "—") },
  { name: "Lambda serverless", beginner: "Event-driven functions; pay per invoke.", intermediate: "Cold starts; provisioned concurrency.", advanced: "Lambda@Edge for CloudFront.", debug: builders.debug(T, "lambda", "Function times out at 3s.", ["Increase timeout/memory", "Disable VPC", "Delete code"], "Increase timeout/memory", "Memory also adds CPU.") },
  { name: "VPC networking", beginner: "Subnets public/private; route tables; IGW/NAT.", intermediate: "Security groups stateful vs NACLs stateless.", advanced: "VPC endpoints for private S3 access.", why: "Architect interviews." },
  { name: "RDS and DynamoDB", beginner: "RDS managed SQL; Multi-AZ for HA.", intermediate: "DynamoDB partition key design.", advanced: "Global tables cross-region.", scenario: builders.scenario(T, "db", "Connection storm on RDS.", "RDS Proxy; pool in app; tune max_connections.", "Serverless burst.") },
  { name: "CloudWatch observability", beginner: "Metrics alarms SNS notifications.", intermediate: "Logs insights queries; dashboards.", advanced: "X-Ray tracing distributed requests.", why: "Ops interviews." },
  { name: "SQS SNS messaging", beginner: "SQS queues decouple services.", intermediate: "DLQ for failed messages.", advanced: "FIFO ordering and deduplication.", coding: builders.coding(T, "Fan-out pattern?", "SNS topic → multiple SQS subscribers.", "Event broadcast.", "", "—", "—") },
  { name: "API Gateway", beginner: "REST/HTTP APIs front Lambda/ECS.", intermediate: "Throttling and API keys usage plans.", advanced: "Cognito authorizer JWT.", scenario: builders.scenario(T, "api", "502 from API Gateway.", "Check integration timeout/backend errors.", "Logs enable.") },
  { name: "Well-Architected pillars", beginner: "Operational excellence, security, reliability, performance, cost.", intermediate: "Design for failure multi-AZ.", advanced: "Chaos engineering in staging.", bestPractice: { question: "Cost optimization quick win?", answer: "Right-size instances; S3 lifecycle; idle resource cleanup.", explanation: "FinOps." } },
  { name: "Route53 and CloudFront", beginner: "DNS routing policies weighted/latency.", intermediate: "CloudFront CDN caches at edge.", advanced: "Signed URLs/cookies for private content.", why: "Global apps." },
  { name: "secrets and KMS", beginner: "Secrets Manager rotation.", intermediate: "KMS encrypts data at rest.", advanced: "Envelope encryption pattern.", scenario: builders.scenario(T, "security", "Leaked AWS access key.", "Rotate; deny old; CloudTrail audit; SCP restrict.", "Incident response.") },
]);
