import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "CSS";

export const cssConcepts = buildTechConcepts(T, [
  { name: "flexbox layout", beginner: "display:flex; justify-content; align-items.", intermediate: "flex-grow/shrink/basis; gap property.", advanced: "Order only for visual not logical reorder a11y.", mcq: builders.mcq(T, "flex", "Center child horizontally and vertically?", ["text-align", "justify+align on flex container", "float"], "justify+align on flex container", "Flex container axes.") },
  { name: "CSS grid", beginner: "grid-template-columns rows; gap.", intermediate: "fr unit; minmax(); auto-fit.", advanced: "Subgrid for nested alignment.", coding: builders.coding(T, "Holy grail layout with grid?", "grid-template areas or columns 1fr auto 1fr.", "Modern replacement.", "", "—", "—") },
  { name: "specificity and cascade", beginner: "inline > id > class > element; !important wins.", intermediate: ":where() zero specificity useful for resets.", advanced: "@layer orders cascade layers.", debug: builders.debug(T, "cascade", "Style not applying.", ["Higher specificity elsewhere", "Browser broken", "HTML invalid"], "Higher specificity elsewhere", "DevTools computed styles.") },
  { name: "box model", beginner: "content padding border margin; box-sizing border-box.", intermediate: "Margin collapse vertical adjacent blocks.", advanced: "contain property isolates layout/paint.", scenario: builders.scenario(T, "layout", "Unexpected horizontal scroll.", "100vw includes scrollbar; fixed width overflow.", "Audit overflow-x.") },
  { name: "responsive design media queries", beginner: "Mobile-first min-width breakpoints.", intermediate: "container queries @container.", advanced: "clamp() fluid typography.", why: "Every UI interview." },
  { name: "CSS animations transitions", beginner: "transition property duration easing.", intermediate: "prefers-reduced-motion respect a11y.", advanced: "@keyframes for complex animations.", coding: builders.coding(T, "Animate height:auto smoothly?", "max-height trick or grid 0fr/1fr or JS measure.", "Height auto not animatable directly.", "", "—", "—") },
  { name: "positioning z-index stacking", beginner: "relative absolute fixed sticky contexts.", intermediate: "Stacking contexts from opacity/transform.", advanced: "isolation: isolate creates context.", scenario: builders.scenario(T, "z-index", "Modal behind header.", "Raise modal portal; check parent stacking context.", "Create portal root.") },
  { name: "CSS variables custom properties", beginner: "--color defined on :root.", intermediate: "Theming dark mode with data-theme.", advanced: "Register custom properties with @property.", why: "Design systems." },
  { name: "pseudo elements classes", beginner: "::before ::after need content.", intermediate: ":focus-visible better than :focus only.", advanced: "::backdrop for modal overlays.", bestPractice: { question: "Focus styles should?", answer: "Be visible for keyboard users; don't remove outline without replacement.", explanation: "WCAG." } },
  { name: "modern selectors :has", beginner: ":has() parent selector from children state.", intermediate: "Complex selectors impact performance — profile.", advanced: "Combine with :not for exclusions.", why: "CSS4 interviews." },
  { name: "performance containment will-change", beginner: "Avoid animating layout properties width/top.", intermediate: "transform/opacity GPU friendly.", advanced: "content-visibility auto defers offscreen render.", scenario: builders.scenario(T, "perf", "Scroll jank on long list.", "content-visibility; virtualize list; contain paint.", "Measure FPS.") },
  { name: "CSS architecture BEM", beginner: "Block__element--modifier naming.", intermediate: "CSS modules scope locally.", advanced: "Tailwind utility-first trade-offs.", coding: builders.coding(T, "Prevent global style leaks in SPA?", "CSS modules, shadow DOM, or scoped libs.", "Team convention.", "", "—", "—") },
]);
