import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "cybersecurity";

export const cyberConcepts = buildTechConcepts(T, [
  {
    name: "CIA triad",
    beginner: "Confidentiality, Integrity, Availability.",
    intermediate: "Balance controls per asset risk.",
    advanced: "Zero trust assumes breach.",
    mcq: builders.mcq(T, "CIA", "Ransomware primarily threatens?", ["Confidentiality only", "Availability", "Integrity only"], "Availability", "Encryption denies access."),
  },
  {
    name: "OWASP Top 10",
    beginner: "Injection, broken auth, XSS, misconfig common web risks.",
    intermediate: "Mitigate with input validation, parameterized queries, CSP.",
    advanced: "Threat modeling per feature.",
    scenario: builders.scenario(T, "web", "Stored XSS in comments.", "Encode output, CSP, sanitize HTML, HttpOnly cookies.", "Defense in depth."),
  },
  {
    name: "SQL injection",
    beginner: "Untrusted input alters SQL logic.",
    intermediate: "Prepared statements; ORM parameterization.",
    advanced: "WAF secondary layer not primary fix.",
    coding: builders.coding(T, "Safe login query approach.", "PreparedStatement with ? placeholders; never concatenate.", "Parameterized queries.", "", "—", "—"),
  },
  {
    name: "authentication vs authorization",
    beginner: "AuthN who you are; AuthZ what you can do.",
    intermediate: "MFA raises AuthN assurance.",
    advanced: "ABAC/RBAC for fine-grained AuthZ.",
    why: "Every security interview.",
  },
  {
    name: "encryption at rest and transit",
    beginner: "TLS for transit; AES for data at rest.",
    intermediate: "Key management with KMS/HSM.",
    advanced: "Rotation and envelope encryption.",
    why: "Compliance basics.",
  },
  {
    name: "phishing and social engineering",
    beginner: "User deception to steal credentials.",
    intermediate: "Security awareness training; reporting.",
    advanced: "Simulated phishing programs.",
    scenario: builders.scenario(T, "phish", "Employee clicked fake O365 link.", "Isolate device, reset creds, scan, educate.", "Incident response steps."),
  },
  {
    name: "network security",
    beginner: "Firewalls, segmentation, VPN.",
    intermediate: "IDS/IPS detection vs prevention.",
    advanced: "East-west micro-segmentation.",
    why: "Infrastructure security.",
  },
  {
    name: "DDoS",
    beginner: "Overwhelm service with traffic.",
    intermediate: "CDN scrubbing rate limits.",
    advanced: "Anycast and autoscale mitigations.",
    debug: builders.debug(T, "DDoS", "Sudden traffic spike legitimate?", ["Analyze geo, user-agent, auth patterns", "Block all traffic", "Delete DNS"], "Analyze geo, user-agent, auth patterns", "Distinguish attack vs viral."),
  },
  {
    name: "penetration testing",
    beginner: "Authorized simulated attacks find vulns.",
    intermediate: "Scope rules of engagement.",
    advanced: "Red team vs bug bounty programs.",
    why: "Offensive security roles.",
  },
  {
    name: "incident response",
    beginner: "Prepare, detect, contain, eradicate, recover, lessons.",
    intermediate: "Preserve forensic evidence chain.",
    advanced: "Tabletop exercises regularly.",
    scenario: builders.scenario(T, "IR", "Ransomware encrypted file server.", "Isolate, backups restore, law enforcement, root cause.", "Playbook driven."),
  },
  {
    name: "password storage",
    beginner: "Never plaintext; use bcrypt/argon2 with salt.",
    intermediate: "Pepper in HSM for extra secret.",
    advanced: "Passkeys WebAuthn reduce password risk.",
    bestPractice: { question: "Bad password storage?", answer: "MD5/sha1 without salt, reversible encryption.", explanation: "Use slow hashes." },
  },
  {
    name: "TLS and certificates",
    beginner: "HTTPS encrypts channel; cert proves server identity.",
    intermediate: "Certificate pinning mobile apps.",
    advanced: "mTLS service-to-service.",
    why: "Transport security.",
  },
  {
    name: "malware types",
    beginner: "Virus worm trojan ransomware spyware.",
    intermediate: "EDR behavioral detection.",
    advanced: "Sandbox detonation analysis.",
    why: "SOC analyst path.",
  },
  {
    name: "risk assessment",
    beginner: "Risk = likelihood × impact.",
    intermediate: "Qualitative vs quantitative scoring.",
    advanced: "Risk register and treatment plans.",
    why: "GRC interviews.",
  },
  {
    name: "compliance GDPR HIPAA",
    beginner: "Data minimization consent breach notification.",
    intermediate: "DPIA for high-risk processing.",
    advanced: "Cross-border transfer mechanisms.",
    why: "Regulated industries.",
  },
  {
    name: "cloud security shared responsibility",
    beginner: "Provider secures cloud; customer secures data/config.",
    intermediate: "IAM least privilege S3 public block.",
    advanced: "CSPM continuous misconfig scanning.",
    why: "AWS/Azure hiring.",
  },
  {
    name: "supply chain attacks",
    beginner: "Compromise dependencies or build pipeline.",
    intermediate: "SBOM signing verify artifacts.",
    advanced: "SLSA framework levels.",
    scenario: builders.scenario(T, "supply", "Compromised npm package detected.", "Pin versions, audit, rotate secrets, rebuild.", "SolarWinds lesson."),
  },
  {
    name: "security logging SIEM",
    beginner: "Centralize logs correlate alerts.",
    intermediate: "Use cases for brute force, privilege escalation.",
    advanced: "SOAR automated response playbooks.",
    why: "Blue team operations.",
  },
]);
