import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "Docker";

export const dockerConcepts = buildTechConcepts(T, [
  { name: "images vs containers", beginner: "Image is immutable template; container is running instance.", intermediate: "Layers cached; change Dockerfile order for cache hits.", advanced: "Distroless/minimal images reduce attack surface.", mcq: builders.mcq(T, "docker", "Command to run container from image?", ["docker build", "docker run", "docker push"], "docker run", "Creates writable layer.") },
  { name: "Dockerfile best practices", beginner: "FROM, WORKDIR, COPY, RUN, CMD/ENTRYPOINT.", intermediate: "Multi-stage build separates build and runtime.", advanced: "Non-root USER; read-only rootfs where possible.", coding: builders.coding(T, "Shrink Node production image?", "Multi-stage: build in node:20, copy dist to node:20-alpine.", "Smaller attack surface.", "", "—", "—") },
  { name: "Docker Compose", beginner: "services networks volumes in compose.yml.", intermediate: "depends_on vs healthcheck wait.", advanced: "Profiles for dev vs test stacks.", scenario: builders.scenario(T, "compose", "App can't reach DB on startup.", "Wait for DB healthcheck; retry connection.", "Race at boot.") },
  { name: "networking bridge host", beginner: "Default bridge network isolates containers.", intermediate: "Published ports -p host:container.", advanced: "Custom networks for service discovery by name.", why: "Local dev parity." },
  { name: "volumes and bind mounts", beginner: "Volumes persist data beyond container life.", intermediate: "Bind mount source code for hot reload dev.", advanced: "Named volumes backup strategies.", debug: builders.debug(T, "data", "DB data lost after restart.", ["Used ephemeral container FS", "Forgot volume", "Wrong image"], "Forgot volume", "docker volume ls.") },
  { name: "container security", beginner: "Don't run as root; scan images with Trivy.", intermediate: "Secrets via env files not baked in image.", advanced: "Read-only filesystem except /tmp.", scenario: builders.scenario(T, "security", "Image CVE critical in base.", "Rebuild base; pin digests; patch pipeline.", "Supply chain.") },
  { name: "resource limits", beginner: "docker run --memory --cpus.", intermediate: "Kubernetes inherits limits from requests/limits.", advanced: "OOM killed container exit 137.", why: "Production stability." },
  { name: "logging and debugging", beginner: "docker logs -f container.", intermediate: "docker exec -it sh for shell.", advanced: "Centralize logs to ELK/Datadog.", coding: builders.coding(T, "Debug container exit code 1?", "docker logs; run interactively; check CMD.", "Non-zero exit.", "", "—", "—") },
  { name: "registry and tags", beginner: "docker push to Docker Hub/ECR/GCR.", intermediate: "Tag with git sha not latest only.", advanced: "Image signing cosign.", why: "CI/CD pipelines." },
  { name: "orchestration handoff to K8s", beginner: "Compose good for dev; K8s for prod scale.", intermediate: "Kompose converts compose cautiously.", advanced: "Helm charts package K8s apps.", bestPractice: { question: "Never use latest tag in prod because?", answer: "Non-reproducible deploys; surprise breaking changes.", explanation: "Pin versions." } },
  { name: "healthchecks", beginner: "HEALTHCHECK in Dockerfile or compose.", intermediate: "curl/wget endpoint /health.", advanced: "Startup vs liveness vs readiness in K8s.", scenario: builders.scenario(T, "deploy", "LB routes to starting container.", "Readiness probe until app ready.", "Premature traffic.") },
  { name: "build cache and CI", beginner: "docker build -t tag . with context size matters.", intermediate: "BuildKit cache mounts speed npm ci.", advanced: "Remote cache in CI (gha, ecr).", why: "Pipeline speed interviews." },
]);
