/** JavaScript — unique interview concepts (100+ questions via conceptBank expansion) */
export const javascriptConcepts = [
  {
    name: "let, const, and var",
    beginner:
      "var is function-scoped and hoisted; let and const are block-scoped. const prevents reassignment but not mutation of objects.",
    intermediate:
      "Temporal dead zone prevents let/const access before declaration. Use const by default, let when rebinding, avoid var in modern code.",
    advanced:
      "Hoisting interacts with closures and loops; classic var-in-loop bug vs let capturing per iteration. Bundlers and linters enforce const-first style.",
    why: "Scope rules prevent subtle production bugs in async UI code.",
    example: "React hooks and loop counters rely on block scope with let.",
    mistake: "Assuming const makes nested object properties immutable.",
    tip: "Mention TDZ and one real bug you fixed with let.",
    mcq: {
      question: "What happens when you access a let variable before its declaration?",
      options: ["undefined", "ReferenceError (TDZ)", "null", "Empty string"],
      answer: "ReferenceError (TDZ)",
      explanation: "let/const exist in TDZ from start of block until declaration line executes.",
    },
    output: {
      question: "What is logged?\nfor (var i=0;i<3;i++) setTimeout(()=>console.log(i),0);\n(Assume browser timers.)",
      options: ["0,1,2", "3,3,3", "undefined ×3", "Error"],
      answer: "3,3,3",
      explanation: "var is function-scoped; one shared i ends at 3. let would log 0,1,2.",
      code: "for (var i=0;i<3;i++) setTimeout(()=>console.log(i),0);",
    },
    coding: {
      question: "Write a function `unique(arr)` returning duplicates removed preserving order (no Set).",
      answer: "Use indexOf while building result array — O(n²) acceptable for small n; mention Set for production.",
      explanation: "Filter/indexOf or Map for O(n). Discuss trade-offs.",
      code: "function unique(arr){return arr.filter((v,i)=>arr.indexOf(v)===i);}",
      time: "O(n²) naive / O(n) with Map",
      space: "O(n)",
    },
    scenario: {
      question: "Production bug: UI shows stale prices after navigation. How could var vs let cause this?",
      answer: "Shared var in event handlers or loops retaining wrong index/state; fix with block scope and cleanup in useEffect.",
      explanation: "Link closure scope to stale state patterns.",
    },
  },
  {
    name: "closures",
    beginner: "A closure is a function that remembers variables from where it was created.",
    intermediate:
      "Closures power callbacks, module patterns, and partial application. Memory stays until references released.",
    advanced: "Closure retention can leak DOM nodes if handlers not removed; weak references and cleanup matter at scale.",
    why: "Core to JavaScript interviews and every frontend framework.",
    example: "Debounced search stores timer id in closure scope.",
    mistake: "Creating closures inside loops without understanding captured variables.",
    tip: "Draw lexical scope chain on whiteboard.",
    mcq: {
      question: "Which best describes a JavaScript closure?",
      options: [
        "A function bundled with its lexical environment",
        "A CSS animation",
        "A Promise executor",
        "A type coercion rule",
      ],
      answer: "A function bundled with its lexical environment",
      explanation: "Inner function closes over outer bindings.",
    },
    debug: {
      question: "Memory grows on SPA route changes. What closure-related cause do you check?",
      options: [
        "Event listeners not removed",
        "Missing semicolons only",
        "CSS z-index",
        "HTTP caching",
      ],
      answer: "Event listeners not removed",
      explanation: "Handlers hold closures referencing detached DOM.",
    },
    scenario: {
      question: "Design a rate-limiter for API calls using closures (conceptual).",
      answer: "Outer function holds lastCall timestamp; inner returns whether call allowed.",
      explanation: "Demonstrate module pattern and state encapsulation.",
    },
  },
  {
    name: "event loop and async",
    beginner: "JS is single-threaded; the event loop schedules macrotasks and microtasks.",
    intermediate: "Promises run microtasks before next paint; setTimeout is macrotask. await splits async functions.",
    advanced: "Starvation possible if microtasks recurse; understand Node vs browser differences for I/O.",
    why: "Explains UI freezes and async interview puzzles.",
    example: "await fetch then DOM update runs as microtasks.",
    mistake: "Thinking setTimeout(0) runs before Promise.then always in every host.",
    tip: "State order: sync → microtasks → macrotask.",
    output: {
      question: "Order of logs?\nconsole.log(1); Promise.resolve().then(()=>console.log(2)); setTimeout(()=>console.log(3)); console.log(4);",
      options: ["1,2,3,4", "1,4,2,3", "1,4,3,2", "4,1,2,3"],
      answer: "1,4,2,3",
      explanation: "Sync 1,4 then microtask 2 then macrotask 3.",
      code: "console.log(1); Promise.resolve().then(()=>console.log(2)); setTimeout(()=>console.log(3)); console.log(4);",
    },
    scenario: {
      question: "Page janks during heavy JSON parse. How do you use the event loop to fix UX?",
      answer: "Chunk work with requestIdleCallback/setTimeout or Web Worker; yield to render.",
      explanation: "Don't block main thread.",
    },
  },
  {
    name: "Promises and async/await",
    beginner: "Promises represent future values; async/await is syntactic sugar over Promises.",
    intermediate: "Chain with then/catch; Promise.all for parallel, allSettled for partial success.",
    advanced: "Unhandled rejections crash Node; cancellation via AbortController; avoid async void.",
    why: "Modern APIs and React data fetching depend on this.",
    example: "fetch with await and try/catch in route loaders.",
    mistake: "Forgetting return inside then causing undefined downstream.",
    tip: "Mention error boundaries + async data loading.",
    coding: {
      question: "Implement `delay(ms)` returning a Promise and use it in `retry(fn, n)`.",
      answer: "delay resolves after ms; retry loops on failure with backoff optional.",
      explanation: "Show Promise constructor or await delay in loop.",
      code: "const delay=(ms)=>new Promise(r=>setTimeout(r,ms));",
    },
    debug: {
      question: "UnhandledPromiseRejectionWarning in Node after deploy. First steps?",
      options: ["Add global handler & trace stack", "Disable promises", "Remove async", "Upgrade CSS"],
      answer: "Add global handler & trace stack",
      explanation: "Find missing catch on async path.",
    },
  },
  {
    name: "prototypes and inheritance",
    beginner: "Objects delegate to prototypes via internal [[Prototype]] link.",
    intermediate: "Classes are syntactic sugar; methods live on prototype for memory efficiency.",
    advanced: "Understand Object.create, hasOwnProperty vs in, and composition over deep chains.",
    why: "Still asked even with class syntax everywhere.",
    example: "Extending Error types for API errors.",
    mistake: "Modifying Object.prototype globally.",
    tip: "Compare class fields vs prototype methods.",
    mcq: {
      question: "How does JavaScript look up `obj.toString()` if not own property?",
      options: ["Prototype chain", "Compiler injection", "DNS", "Webpack"],
      answer: "Prototype chain",
      explanation: "Walks [[Prototype]] until found or null.",
    },
  },
  {
    name: "this binding",
    beginner: "this depends on call site: method, plain call, new, call/apply/bind.",
    intermediate: "Arrow functions lexically bind this; loss common when passing callbacks.",
    advanced: "Strict mode leaves undefined this on plain calls; track in event APIs.",
    why: "Classic interview trick questions.",
    example: "bind click handler in class components (legacy).",
    mistake: "Using arrow as object method expecting dynamic this.",
    tip: "List four binding rules clearly.",
    coding: {
      question: "Fix: `const user={name:'A', greet(){console.log(this.name)}}; const g=user.greet; g();`",
      answer: "Use g.call(user) or greet: () => or bind in constructor.",
      explanation: "Implicit loss on extraction.",
    },
  },
  {
    name: "ES modules vs CommonJS",
    beginner: "import/export are static; require is dynamic CommonJS in Node.",
    intermediate: "Tree-shaking needs ESM; __dirname not in ESM without import.meta.",
    advanced: "Dual packages hazard; type module in package.json affects interop.",
    why: "Full-stack JS roles expect both.",
    example: "Vite ESM frontend importing CJS utils carefully.",
    mistake: "Mixing require and import in same file incorrectly.",
    scenario: {
      question: "Bundle size jumped after importing lodash. Steps?",
      answer: "Import specific paths, lodash-es, or alternative; analyze bundle analyzer.",
      explanation: "ESM tree-shaking vs full CJS require.",
    },
  },
  {
    name: "type coercion and equality",
    beginner: "== coerces types; === does not. Falsy: false,0,'',null,undefined,NaN.",
    intermediate: "Object.is handles NaN; Map keys use SameValueZero.",
    advanced: "ToPrimitive for object comparison in == paths.",
    why: "Output prediction questions love this.",
    example: "Form validation checking empty strings.",
    mistake: "if (x) when x can be 0 valid value.",
    output: {
      question: "Result of: [] == false",
      options: ["true", "false", "TypeError", "undefined"],
      answer: "true",
      explanation: "Both coerce to 0 in == comparison path.",
    },
  },
  {
    name: "arrays and functional methods",
    beginner: "map/filter/reduce transform arrays immutably when not mutating in place.",
    intermediate: "reduce builds aggregations; flatMap maps+flattens; some/every short-circuit.",
    advanced: "Big-O of chained methods; generator alternatives for memory.",
    why: "Daily React state transforms.",
    example: "Deriving chart data with reduce from API rows.",
    mistake: "Using map without return value accidentally.",
    coding: {
      question: "Implement flatten one level for nested arrays using reduce.",
      answer: "reduce concat with spread or concat flat one level.",
      explanation: "Discuss recursive deep flatten separately.",
      time: "O(n)",
      space: "O(n)",
    },
  },
  {
    name: "destructuring and spread",
    beginner: "Destructuring pulls fields; spread copies iterables/objects shallowly.",
    intermediate: "Rest params collect remaining; default values apply when undefined.",
    advanced: "Shallow copy pitfalls with nested objects in React state updates.",
    why: "React props/state patterns.",
    example: "setState(prev => ({...prev, loading: true})).",
    mistake: "Spreading nested object expecting deep clone.",
  },
  {
    name: "error handling",
    beginner: "try/catch for sync; catch on promises for async.",
    intermediate: "Custom errors extend Error; rethrow after logging.",
    advanced: "Centralized error middleware in Express; error boundaries in React.",
    why: "Production reliability interviews.",
    scenario: {
      question: "API returns 500 intermittently. Client-side strategy?",
      answer: "Retry with backoff, circuit breaker, user messaging, correlation ids.",
      explanation: "Resilience patterns.",
    },
  },
  {
    name: "fetch and CORS",
    beginner: "fetch returns promises; CORS enforced by browser for cross-origin.",
    intermediate: "Credentials mode and preflight for non-simple requests.",
    advanced: "Proxy in dev; BFF pattern for hiding tokens.",
    why: "Full-stack JS interviews.",
    mistake: "Exposing API keys in frontend bundle.",
    debug: {
      question: "CORS error only in browser not Postman. Meaning?",
      options: ["Browser enforces CORS", "Server down", "DNS broken", "JWT expired"],
      answer: "Browser enforces CORS",
      explanation: "Postman is not a browser CORS client.",
    },
  },
  {
    name: "memory and garbage collection",
    beginner: "GC frees unreachable objects; global references prevent collection.",
    intermediate: "Detached DOM and closures cause leaks in SPAs.",
    advanced: "Heap snapshots in Chrome DevTools; WeakMap for caches.",
    why: "Senior frontend differentiator.",
    scenario: {
      question: "Dashboard tab slows after hours. Approach?",
      answer: "Heap snapshot diff, listener audit, profile components re-rendering.",
      explanation: "Systematic leak hunt.",
    },
  },
  {
    name: "testing fundamentals",
    beginner: "Unit tests isolate functions; mocks replace dependencies.",
    intermediate: "Jest fake timers for async; testing-library focuses user behavior.",
    advanced: "Flaky tests from real timers/network; contract tests for APIs.",
    why: "Quality bar in product companies.",
    bestPractice: {
      question: "What should a good React unit test assert?",
      answer: "User-visible outcomes, not implementation details like state variable names.",
      explanation: "Testing Library philosophy.",
    },
  },
  {
    name: "security basics (XSS)",
    beginner: "Never insert untrusted HTML without sanitization.",
    intermediate: "CSP headers, escape output, avoid dangerouslySetInnerHTML.",
    advanced: "DOM-based vs stored XSS; JWT in memory vs localStorage trade-offs.",
    why: "Web security is interview standard.",
    scenario: {
      question: "User comment appears as script execution. Fix?",
      answer: "Sanitize HTML, encode output, CSP, use safe templating.",
      explanation: "XSS mitigation stack.",
    },
  },
  {
    name: "performance optimization",
    beginner: "Avoid unnecessary work: memoize, debounce, virtualize lists.",
    intermediate: "Lighthouse metrics: LCP, FID, CLS; code splitting.",
    advanced: "Main thread profiling; worker for heavy compute.",
    why: "Frontend senior interviews.",
    coding: {
      question: "Why debounce search input? Describe implementation sketch.",
      answer: "Wait until typing pauses before API call; closure holds timer id, clear on each keystroke.",
      explanation: "Reduces load and race conditions.",
    },
  },
  {
    name: "design patterns in JS",
    beginner: "Module pattern encapsulates private state via closures.",
    intermediate: "Observer pattern in EventEmitter and React subscriptions.",
    advanced: "Factory vs constructor; dependency injection in large apps.",
    why: "Shows engineering maturity.",
  },
  {
    name: "Map, Set, WeakMap",
    beginner: "Map allows any keys; Set unique values; better for frequent lookups.",
    intermediate: "WeakMap keys are objects GC-collectable — good for private metadata.",
    advanced: "Choose structure based on iteration and key type needs.",
    why: "Beyond plain objects.",
    mcq: {
      question: "When prefer Map over plain object?",
      options: [
        "Non-string keys or frequent arbitrary key types",
        "Always use Map",
        "Never use Map",
        "Only for CSS",
      ],
      answer: "Non-string keys or frequent arbitrary key types",
      explanation: "Map preserves insertion order and key types.",
    },
  },
  {
    name: "generators and iterators",
    beginner: "Generators yield multiple values; pausable with yield.",
    intermediate: "Custom iterables implement Symbol.iterator.",
    advanced: "Async generators for streaming data pipelines.",
    why: "Occasional advanced interview topic.",
  },
  {
    name: "optional chaining and nullish coalescing",
    beginner: "?. stops on null/undefined; ?? defaults only for null/undefined.",
    intermediate: "Prefer ?? over || when 0 or '' are valid.",
    advanced: "Short-circuiting behavior in chained expressions.",
    why: "Modern syntax daily use.",
    output: {
      question: "Value of: 0 ?? 5",
      options: ["0", "5", "undefined", "null"],
      answer: "0",
      explanation: "?? only replaces null/undefined, not 0.",
    },
  },
];
