import { buildTechConcepts } from "./topicBuilder.js";
import { builders } from "./topicBuilder.js";

const T = "Java";

const specs = [
  {
    name: "JVM, JRE, and JDK",
    beginner: "JDK includes compiler and tools; JRE runs bytecode; JVM executes platform-independent bytecode.",
    intermediate: "Class loaders, bytecode verification, and JIT compilation optimize hot paths at runtime.",
    advanced: "Garbage collectors (G1, ZGC) trade throughput vs latency; tuning flags matter for services.",
    why: "Foundation for all Java backend interviews.",
    example: "Spring Boot jar runs on JVM with embedded Tomcat.",
    mistake: "Installing only JRE when you need javac to compile.",
    tip: "Draw JVM memory regions: heap, stack, metaspace.",
    mcq: builders.mcq(T, "JVM", "Which component executes Java bytecode?", ["JDK", "JVM", "Git", "Maven"], "JVM", "JVM interprets/JITs bytecode."),
    scenario: builders.scenario(T, "JVM", "Production service pauses every 30s. What JVM area do you investigate?", "GC logs and pause times — tune collector or heap.", "Link STW pauses to GC."),
  },
  {
    name: "OOP pillars in Java",
    beginner: "Encapsulation hides state; inheritance shares behavior; polymorphism enables one interface many forms.",
    intermediate: "Favor composition over inheritance; interfaces define contracts; abstract classes partial implementation.",
    advanced: "Liskov violations when subclasses break expectations; design for extension via interfaces.",
    why: "OOPs interviews map directly to Java roles.",
    example: "PaymentProcessor interface with Stripe/PayPal implementations.",
    mistake: "Deep inheritance trees instead of strategy pattern.",
    coding: builders.coding(T, "Model `Shape` with `area()` using interface vs abstract class — when choose each?", "Interface when no shared state; abstract when shared code.", "Discuss trade-offs.", "", "O(1)", "O(1)"),
  },
  {
    name: "collections framework",
    beginner: "List ordered, Set unique, Map key-value. ArrayList fast read, LinkedList fast insert middle.",
    intermediate: "HashMap buckets and load factor; TreeMap sorted; ConcurrentHashMap for threads.",
    advanced: "Fail-fast iterators vs concurrent collections; equals/hashCode contract for keys.",
    why: "Daily Java development and coding rounds.",
    example: "Caching user sessions in ConcurrentHashMap.",
    mistake: "Using HashMap from multiple threads without synchronization.",
    mcq: builders.mcq(T, "collections", "Default load factor of HashMap?", ["0.5", "0.75", "1.0", "2.0"], "0.75", "Rehash when size exceeds capacity × load factor."),
    output: builders.output(T, "What fails if key lacks hashCode override when using HashMap?", "Keys may not be found after retrieval", ["Works fine", "Duplicate keys only", "Compile error"], "Keys may not be found after retrieval", "Broken equals/hashCode contract."),
  },
  {
    name: "exception handling",
    beginner: "Checked exceptions must be handled or declared; unchecked extend RuntimeException.",
    intermediate: "try-with-resources auto-closes AutoCloseable; never swallow exceptions.",
    advanced: "Global handlers in Spring @ControllerAdvice; wrap low-level exceptions with context.",
    why: "Reliable APIs and clean failure modes.",
    scenario: builders.scenario(T, "exceptions", "REST API returns 500 without logs. Steps?", "Log stack trace with correlation id; map to ProblemDetail response.", "Observability first."),
  },
  {
    name: "multithreading",
    beginner: "Threads share heap; synchronize on locks for mutual exclusion.",
    intermediate: "ExecutorService manages pools; Callable returns values; avoid thread per request.",
    advanced: "java.util.concurrent locks, atomics, CompletableFuture composition.",
    why: "Backend scale interviews.",
    debug: builders.debug(T, "Race condition suspected. First tool?", ["Thread dump / logs", "CSS linter", "Maven clean", "JUnit only"], "Thread dump / logs", "Inspect shared mutable state."),
  },
  {
    name: "Java 8+ streams and lambdas",
    beginner: "Lambdas implement functional interfaces; streams process collections declaratively.",
    intermediate: "map/filter/reduce; parallel streams use ForkJoin — use carefully.",
    advanced: "Streams are not always faster; boxing costs; prefer clarity.",
    coding: builders.coding(T, "Count words in a file using streams (approach).", "lines → flatMap split → groupingBy count", "Mention Files.lines and collectors.", "", "O(n)", "O(n)"),
  },
  {
    name: "Spring Boot fundamentals",
    beginner: "Auto-configuration sets up beans; starters bundle dependencies.",
    intermediate: "Dependency injection via constructor; @RestController exposes HTTP.",
    advanced: "Actuator health metrics; profiles for dev/prod configuration.",
    why: "Spring Boot is default for Java hiring.",
    scenario: builders.scenario(T, "Spring", "Bean not injected — NullPointer in controller. Causes?", "Missing @Component scan, wrong package, or circular dependency.", "Check component scan path."),
  },
  {
    name: "JPA and Hibernate",
    beginner: "Entities map tables; EntityManager persists objects.",
    intermediate: "Lazy loading avoids N+1 with fetch joins; transactions boundary matters.",
    advanced: "2nd level cache; optimistic locking with @Version.",
    mistake: "LazyInitializationException outside session.",
    mcq: builders.mcq(T, "JPA", "What causes LazyInitializationException?", ["Access lazy relation outside transaction/session", "Wrong Java version", "Missing main method"], "Access lazy relation outside transaction/session", "Session closed before access."),
  },
  {
    name: "REST API design",
    beginner: "Resources as nouns; HTTP verbs map to actions; status codes convey outcome.",
    intermediate: "DTOs decouple API from entities; validation with Bean Validation.",
    advanced: "Idempotency for PUT; pagination; HATEOAS optional.",
    why: "Microservice interviews.",
  },
  {
    name: "Maven/Gradle builds",
    beginner: "Dependencies declared in pom/build.gradle; lifecycle phases compile package install.",
    intermediate: "Transitive dependencies; scope compile vs test vs provided.",
    advanced: "Multi-module projects; BOM for version alignment.",
    why: "Build tooling literacy.",
  },
  {
    name: "JUnit testing",
    beginner: "@Test methods assert behavior; @BeforeEach sets up fixtures.",
    intermediate: "Mockito mocks collaborators; integration tests use @SpringBootTest.",
    advanced: "Testcontainers for real DB; avoid testing framework internals.",
    bestPractice: { question: "What makes a good unit test in Java?", answer: "Fast, isolated, deterministic, single behavior.", explanation: "FIRST principles." },
  },
  {
    name: "synchronization and locks",
    beginner: "synchronized keyword mutual exclusion; volatile visibility not atomicity.",
    intermediate: "ReentrantLock try/finally unlock; ReadWriteLock for read-heavy.",
    advanced: "Deadlock prevention: lock ordering; jstack diagnosis.",
    why: "Concurrency depth questions.",
  },
  {
    name: "serialization",
    beginner: "Serializable marks classes for byte stream conversion.",
    intermediate: "serialVersionUID for compatibility; prefer JSON in modern APIs.",
    advanced: "Security risks deserializing untrusted data.",
    why: "Legacy enterprise systems.",
  },
  {
    name: "records and sealed classes",
    beginner: "Records immutable data carriers; sealed restrict subclasses.",
    intermediate: "Records auto equals/hashCode/toString.",
    advanced: "Model domain ADTs with sealed + records in Java 17+.",
    why: "Modern Java interviews.",
  },
  {
    name: "garbage collection",
    beginner: "Objects unreachable are collected; generations young/old.",
    intermediate: "G1 default; tune -Xmx -Xms appropriately.",
    advanced: "Analyze GC logs for promotion failures.",
    scenario: builders.scenario(T, "GC", "Heap OutOfMemoryError in batch job.", "Increase heap or fix memory leak; profile heap dump.", "Distinguish leak vs undersized heap."),
  },
  {
    name: "design patterns",
    beginner: "Singleton, Factory, Strategy commonly used in Java enterprise apps.",
    intermediate: "Dependency Injection replaces manual singletons in Spring.",
    advanced: "Choose pattern based on change axes not hype.",
    why: "Architecture interviews.",
  },
  {
    name: " JDBC and connection pools",
    beginner: "JDBC talks SQL to databases; PreparedStatement prevents injection.",
    intermediate: "HikariCP pools connections; always close resources.",
    advanced: "Set pool size based on DB max connections / instances.",
    debug: builders.debug(T, "JDBC", "Connection pool exhausted under load.", ["Leak unclosed connections", "Wrong CSS", "CPU only"], "Leak unclosed connections", "Use try-with-resources."),
  },
  {
    name: "microservices basics",
    beginner: "Small deployable services; communicate via HTTP/messaging.",
    intermediate: "Service discovery, config server, circuit breakers.",
    advanced: "Saga patterns for distributed transactions.",
    why: "Java backend career path.",
  },
  {
    name: "security in Java APIs",
    beginner: "Validate input; use PreparedStatement; hash passwords with bcrypt.",
    intermediate: "Spring Security filter chain; JWT validation.",
    advanced: "OWASP top 10 mitigation in APIs.",
    scenario: builders.scenario(T, "security", "JWT rejected intermittently.", "Clock skew, wrong secret rotation, expired refresh flow.", "Token lifecycle."),
  },
  {
    name: "performance profiling",
    beginner: "Measure before optimizing; use profiler not guessing.",
    intermediate: "JFR, VisualVM, async-profiler for hotspots.",
    advanced: "Optimize allocation rate and lock contention.",
    why: "Senior Java signals.",
  },
];

export const javaConcepts = buildTechConcepts(T, specs);
