import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "MongoDB";

export const mongoConcepts = buildTechConcepts(T, [
  {
    name: "documents and BSON",
    beginner: "Flexible JSON-like documents in collections.",
    intermediate: "_id ObjectId; embedded vs referenced docs.",
    advanced: "Schema design impacts query and update patterns.",
    mcq: builders.mcq(T, "docs", "Default primary key type?", ["UUID string", "ObjectId", "Integer"], "ObjectId", "Auto-generated _id."),
  },
  {
    name: "CRUD operations",
    beginner: "insertOne, find, updateOne, deleteOne.",
    intermediate: "update operators $set $inc $push.",
    advanced: "Bulk writes for ingestion throughput.",
    coding: builders.coding(T, "Upsert user by email — describe query.", "updateOne({email}, {$set: fields}, {upsert:true}).", "Idempotent ingestion.", "", "O(log n) with index", "O(1)"),
  },
  {
    name: "indexing",
    beginner: "Indexes speed queries; compound index field order matters.",
    intermediate: "Covered queries; explain() plans.",
    advanced: "Partial and TTL indexes.",
    debug: builders.debug(T, "index", "Query slow despite index.", ["Query not using prefix of compound index", "Too much RAM", "BSON too small"], "Query not using prefix of compound index", "ESR rule."),
  },
  {
    name: "aggregation pipeline",
    beginner: "$match $group $project stages.",
    intermediate: "$lookup joins collections.",
    advanced: "Allow disk use for large pipelines.",
    why: "Analytics in Mongo.",
  },
  {
    name: "schema design patterns",
    beginner: "Embed when read together; reference when shared.",
    intermediate: "Bucket pattern for time series.",
    advanced: "Outlier document growth risks 16MB limit.",
    scenario: builders.scenario(T, "design", "Orders with line items — embed or ref?", "Embed items in order if bounded; reference catalog products.", "Access pattern driven."),
  },
  {
    name: "replication",
    beginner: "Replica set primary + secondaries.",
    intermediate: "Election on primary failure.",
    advanced: "Read preference secondary for analytics.",
    why: "High availability.",
  },
  {
    name: "sharding",
    beginner: "Shard key distributes data across shards.",
    intermediate: "Choose high cardinality even distribution.",
    advanced: "Jumbo chunks and balancer issues.",
    why: "Scale interviews.",
  },
  {
    name: "transactions",
    beginner: "Multi-document ACID in replica set 4.0+.",
    intermediate: "Use sparingly — performance cost.",
    advanced: "Design to avoid cross-shard transactions when possible.",
    why: "Financial apps on Mongo.",
  },
  {
    name: "Mongoose ODM",
    beginner: "Schema, model, middleware hooks.",
    intermediate: "Population for references.",
    advanced: "Validation at schema boundary.",
    why: "Node ecosystem.",
  },
  {
    name: "security",
    beginner: "Auth, roles, network bind IP.",
    intermediate: "Field-level encryption for PII.",
    advanced: "Least privilege DB users.",
    scenario: builders.scenario(T, "security", "Database exposed to internet.", "Firewall, VPC, auth, TLS.", "Common misconfiguration."),
  },
  {
    name: "performance tuning",
    beginner: "Project only needed fields.",
    intermediate: "Avoid unbounded arrays in documents.",
    advanced: "Monitor slow query log.",
    bestPractice: { question: "First step for slow find?", answer: "explain(), check index usage, examine docs examined.", explanation: "Evidence-based tuning." },
  },
  {
    name: "change streams",
    beginner: "Watch collection for inserts/updates.",
    intermediate: "Event-driven sync to search index.",
    advanced: "Resume tokens for reliability.",
    why: "Realtime architectures.",
  },
  {
    name: "Atlas and ops",
    beginner: "Managed MongoDB Atlas clusters.",
    intermediate: "Backups point-in-time restore.",
    advanced: "Global clusters multi-region.",
    why: "Cloud hiring.",
  },
  {
    name: "comparison with SQL",
    beginner: "Mongo flexible schema; SQL strong joins ACID legacy.",
    intermediate: "Choose based on access patterns team skills.",
    advanced: "Polyglot persistence common.",
    why: "Architecture questions.",
  },
  {
    name: "data modeling anti-patterns",
    beginner: "Massive unbounded arrays.",
    intermediate: "Over-normalizing like SQL in document DB.",
    advanced: "Frequent migrations without versioning strategy.",
    why: "Senior design signal.",
  },
  {
    name: "geospatial queries",
    beginner: "2dsphere index for location.",
    intermediate: "$near $geoWithin queries.",
    advanced: "Geohashing at app layer alternative.",
    why: "Location apps.",
  },
  {
    name: "backup and restore",
    beginner: "mongodump/mongorestore dev.",
    intermediate: "Atlas continuous backup.",
    advanced: "Test restore drills regularly.",
    why: "Reliability interviews.",
  },
  {
    name: "memory and WiredTiger",
    beginner: "Cache size affects working set fit.",
    intermediate: "Compression in WiredTiger storage engine.",
    advanced: "Monitor cache eviction metrics.",
    why: "DBA depth.",
  },
]);
