import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "Node.js";

export const nodeConcepts = buildTechConcepts(T, [
  {
    name: "event loop and async I/O",
    beginner: "Node uses libuv thread pool + event loop; non-blocking I/O for concurrency.",
    intermediate: "microtasks (promises) run before next macrotask (timers).",
    advanced: "CPU-bound work blocks loop — offload to worker threads.",
    mcq: builders.mcq(T, "event loop", "Which runs first after current sync code?", ["setTimeout", "Promise.then", "setImmediate"], "Promise.then", "Microtasks drain before timers."),
    scenario: builders.scenario(T, "perf", "API latency spikes under load.", "Profile event loop lag; check blocking sync code.", "Use clinic.js or APM."),
  },
  {
    name: "modules CommonJS vs ESM",
    beginner: "require/module.exports vs import/export.",
    intermediate: "package.json type module enables ESM.",
    advanced: "Interop patterns and dynamic import().",
    why: "Every Node project structure.",
  },
  {
    name: "Express middleware",
    beginner: "Middleware chain req→res; order matters.",
    intermediate: "Error middleware 4-arg handler.",
    advanced: "Rate limit, helmet, compression stack.",
    coding: builders.coding(T, "Order of logging, auth, routes — explain.", "Logging first, auth before protected routes, error handler last.", "Security ordering.", "", "—", "—"),
  },
  {
    name: "REST API design",
    beginner: "Resources, verbs, status codes.",
    intermediate: "Pagination, filtering, versioning.",
    advanced: "Idempotency keys for payments.",
    why: "Backend interviews.",
  },
  {
    name: "error handling",
    beginner: "try/catch async; central error middleware.",
    intermediate: "Operational vs programmer errors.",
    advanced: "Never leak stack traces in production.",
    debug: builders.debug(T, "errors", "Unhandled promise rejection crashes process.", ["Add global handlers", "Return 500 without logging", "Ignore"], "Add global handlers", "process.on unhandledRejection."),
  },
  {
    name: "streams and buffers",
    beginner: "Streams process data chunks; pipes connect.",
    intermediate: "Backpressure with pause/resume.",
    advanced: "Transform streams for ETL pipelines.",
    why: "Large file processing.",
  },
  {
    name: "cluster and PM2",
    beginner: "cluster module forks workers per CPU.",
    intermediate: "PM2 reload zero-downtime.",
    advanced: "Kubernetes replaces manual cluster for scale.",
    why: "Production deployment.",
  },
  {
    name: "environment variables",
    beginner: "dotenv loads .env in dev.",
    intermediate: "Never commit secrets; use vault in prod.",
    advanced: "Validate config at startup with zod/joi.",
    scenario: builders.scenario(T, "config", "Prod uses wrong DB after deploy.", "Check env vars, secrets manager, deployment manifest.", "12-factor config."),
  },
  {
    name: "authentication JWT",
    beginner: "JWT signed token; verify with secret/public key.",
    intermediate: "Short access + refresh rotation.",
    advanced: "HttpOnly cookies reduce XSS token theft.",
    why: "API security standard.",
  },
  {
    name: "MongoDB with Mongoose",
    beginner: "Schemas define shape; models query collections.",
    intermediate: "Indexes for query patterns; lean() for read perf.",
    advanced: "Transactions for multi-doc consistency.",
    why: "MERN stack interviews.",
  },
  {
    name: "testing Node APIs",
    beginner: "supertest hits HTTP without listening port.",
    intermediate: "Mock external services.",
    advanced: "Contract tests with consumers.",
    bestPractice: { question: "What to test in Express route?", answer: "Status, body shape, auth failures, edge inputs.", explanation: "Behavior not implementation." },
  },
  {
    name: "security OWASP basics",
    beginner: "Validate input; sanitize output; helmet headers.",
    intermediate: "Rate limiting, CORS allowlist.",
    advanced: "Dependency audit npm audit.",
    scenario: builders.scenario(T, "security", "NoSQL injection in login.", "Sanitize operators; use typed queries.", "Mongo $gt injection."),
  },
  {
    name: "caching Redis",
    beginner: "Cache-aside pattern with TTL.",
    intermediate: "Invalidate on writes carefully.",
    advanced: "Stampede protection with locks.",
    why: "Performance interviews.",
  },
  {
    name: "WebSockets",
    beginner: "Persistent bidirectional connection.",
    intermediate: "Socket.io rooms and auth.",
    advanced: "Scale with Redis adapter pub/sub.",
    why: "Realtime features.",
  },
  {
    name: "file uploads",
    beginner: "multer handles multipart.",
    intermediate: "Stream to S3; virus scan.",
    advanced: "Presigned URLs offload bandwidth.",
    why: "Common product feature.",
  },
  {
    name: "logging and observability",
    beginner: "Structured JSON logs with correlation id.",
    intermediate: "Winston/Pino levels; centralize in ELK.",
    advanced: "OpenTelemetry traces across services.",
    why: "On-call readiness.",
  },
  {
    name: "graceful shutdown",
    beginner: "SIGTERM stops accepting; finish in-flight requests.",
    intermediate: "Close DB connections cleanly.",
    advanced: "K8s preStop hook drain period.",
    why: "Zero-downtime deploys.",
  },
  {
    name: "package.json and npm",
    beginner: "dependencies vs devDependencies.",
    intermediate: "lockfile ensures reproducible installs.",
    advanced: "Supply chain — pin and audit.",
    why: "Tooling fundamentals.",
  },
]);
