import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "Python";

export const pythonConcepts = buildTechConcepts(T, [
  {
    name: "data types and mutability",
    beginner: "list/dict/set mutable; tuple/str/frozen immutable.",
    intermediate: "Copy with copy vs deepcopy; default mutable args bug.",
    advanced: "Interning small ints/strings; __slots__ for memory.",
    mcq: builders.mcq(T, "types", "What is output of: a=[1,2]; b=a; b.append(3); len(a)", ["2", "3", "Error"], "3", "Shared reference."),
    coding: builders.coding(T, "Reverse a list in-place vs new list — compare approaches.", "slice [::-1] new list; in-place two-pointer swap.", "Clarify mutability.", "", "O(n)", "O(1) in-place"),
  },
  {
    name: "list comprehensions and generators",
    beginner: "Comprehensions build lists concisely; generators yield lazily.",
    intermediate: "Generator expressions save memory on large data.",
    advanced: "itertools for advanced iteration patterns.",
    why: "Pythonic style interviews.",
  },
  {
    name: "OOP in Python",
    beginner: "class, __init__, self; methods define behavior.",
    intermediate: "dunder methods, properties, @classmethod/@staticmethod.",
    advanced: "MRO and multiple inheritance cautiously.",
    why: "Backend Python roles.",
  },
  {
    name: "exceptions",
    beginner: "try/except/else/finally; raise custom exceptions.",
    intermediate: "Specific exceptions; never bare except.",
    advanced: "Exception chaining with raise from.",
    scenario: builders.scenario(T, "exceptions", "API returns 500 on invalid JSON body.", "Return 400 with message; log server-side detail.", "Clear client errors."),
  },
  {
    name: "virtual environments",
    beginner: "venv isolates dependencies per project.",
    intermediate: "requirements.txt vs pyproject.toml.",
    advanced: "Poetry/pip-tools for reproducible builds.",
    why: "Professional workflow.",
  },
  {
    name: "Django/Flask overview",
    beginner: "Django batteries-included; Flask micro flexible.",
    intermediate: "ORM migrations; blueprints in Flask.",
    advanced: "ASGI with async views where appropriate.",
    why: "Python web hiring.",
  },
  {
    name: "decorators",
    beginner: "Functions wrapping functions; @syntax sugar.",
    intermediate: "functools.wraps preserves metadata.",
    advanced: "Parametrized decorators for auth/logging.",
    coding: builders.coding(T, "Write a timing decorator sketch.", "Record start/end, log duration, return wrapped result.", "Show wraps.", "", "O(1) overhead", "O(1)"),
  },
  {
    name: "GIL",
    beginner: "Global Interpreter Lock limits CPU parallelism in threads.",
    intermediate: "Use multiprocessing for CPU-bound work.",
    advanced: "I/O-bound still benefits from asyncio/threads.",
    why: "Python systems interviews.",
  },
  {
    name: "asyncio",
    beginner: "async/await cooperative concurrency for I/O.",
    intermediate: "event loop, tasks, gather.",
    advanced: "Don't mix blocking calls without to_thread.",
    why: "Modern API services.",
  },
  {
    name: "pandas basics",
    beginner: "DataFrame tabular data; read_csv ingest.",
    intermediate: "groupby, merge, handle NaN.",
    advanced: "Vectorize; avoid iterrows in hot paths.",
    why: "Data roles with Python.",
  },
  {
    name: "testing pytest",
    beginner: "assert style tests; fixtures for setup.",
    intermediate: "parametrize cases; monkeypatch mocks.",
    advanced: "coverage + CI integration.",
    bestPractice: { question: "Good pytest test characteristics?", answer: "Isolated, readable name, one behavior.", explanation: "Maintainable tests." },
  },
  {
    name: "packaging and modules",
    beginner: "module is file; package is folder with __init__.",
    intermediate: "relative vs absolute imports.",
    advanced: "Publish package to PyPI structure.",
    why: "Engineering hygiene.",
  },
  {
    name: "memory management",
    beginner: "Reference counting + cycle gc.",
    intermediate: "Profile leaks with tracemalloc.",
    advanced: "Slots and generators reduce footprint.",
    why: "Senior Python.",
  },
  {
    name: "security",
    beginner: "Never eval user input; use parameterized SQL.",
    intermediate: "secrets module for tokens.",
    advanced: "Bandit linting for security issues.",
    scenario: builders.scenario(T, "security", "Pickle load from user upload.", "Never — arbitrary code execution; use safe formats.", "Deserialization risks."),
  },
  {
    name: "type hints",
    beginner: "Annotations document types; mypy checks.",
    intermediate: "Optional, Union, generics.",
    advanced: "Gradual typing in large codebases.",
    why: "Modern Python shops.",
  },
  {
    name: "file I/O and pathlib",
    beginner: "open/read/write; with closes files.",
    intermediate: "pathlib for cross-platform paths.",
    advanced: "Streaming large files line by line.",
    why: "Scripting interviews.",
  },
  {
    name: "APIs with FastAPI",
    beginner: "Path operations; Pydantic models validate.",
    intermediate: "Dependency injection for DB sessions.",
    advanced: "OpenAPI auto docs; background tasks.",
    why: "Fast-growing stack.",
  },
  {
    name: "algorithm interview patterns",
    beginner: "Use dict for frequency; two-pointer technique.",
    intermediate: "bisect, heapq for ordered problems.",
    advanced: "Know when O(n log n) sort is simplest win.",
    coding: builders.coding(T, "Two-sum with hash map approach.", "Store complement in dict while iterating.", "O(n) time.", "", "O(n)", "O(n)"),
  },
]);
