import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "React";

export const reactConcepts = buildTechConcepts(T, [
  {
    name: "components and JSX",
    beginner: "Components are functions returning UI; JSX compiles to React.createElement calls.",
    intermediate: "One-way data flow from parent props to children; composition over inheritance.",
    advanced: "Server Components (RSC) split server/client boundaries in Next.js apps.",
    why: "Core React mental model.",
    example: "Page layout composed of Header, Sidebar, Content components.",
    mistake: "Mutating props or state directly.",
    mcq: builders.mcq(T, "JSX", "Why must React components not mutate props?", ["Props are read-only", "Props are global", "JSX forbids it"], "Props are read-only", "Predictable rendering."),
  },
  {
    name: "useState and useEffect",
    beginner: "useState triggers re-render on update; useEffect runs side effects after paint.",
    intermediate: "Dependency array controls effect runs; cleanup functions prevent leaks.",
    advanced: "StrictMode double-invokes effects in dev to surface bugs.",
    why: "Hooks appear in every interview.",
    scenario: builders.scenario(T, "hooks", "Infinite API loop in useEffect. Cause?", "Missing/wrong dependency array causing effect every render.", "Show minimal reproduction."),
    coding: builders.coding(T, "Fetch user profile on mount with loading/error states — describe structure.", "useEffect + useState for data/status; abort controller on unmount.", "Mention race handling.", "", "O(1) network", "O(1)"),
  },
  {
    name: "virtual DOM and reconciliation",
    beginner: "React diffs virtual tree to update real DOM efficiently.",
    intermediate: "Keys help list reconciliation identify items.",
    advanced: "Understand when reconciliation causes unnecessary re-renders.",
    why: "Explains performance questions.",
    mistake: "Using array index as key for dynamic lists.",
  },
  {
    name: "props vs state",
    beginner: "Props external; state internal and mutable via setState.",
    intermediate: "Lift state up when siblings need shared data.",
    advanced: "Colocate state at lowest level needed.",
    why: "Architecture interviews.",
  },
  {
    name: "context API",
    beginner: "Context passes data without prop drilling.",
    intermediate: "Split contexts to avoid broad re-renders.",
    advanced: "Prefer composition or state libraries for complex global state.",
    why: "Mid-size app patterns.",
  },
  {
    name: "React Router",
    beginner: "Client-side routes map URLs to components.",
    intermediate: "Nested routes, loaders, protected routes.",
    advanced: "Data routers prefetch with suspense boundaries.",
    why: "SPA navigation.",
  },
  {
    name: "forms controlled components",
    beginner: "Value controlled by React state via onChange.",
    intermediate: "Validation on blur/submit; accessible labels.",
    advanced: "React Hook Form reduces re-renders for large forms.",
    why: "Product UI work.",
  },
  {
    name: "performance memoization",
    beginner: "React.memo skips render if props shallow-equal.",
    intermediate: "useMemo/useCallback cache values/functions.",
    advanced: "Profile before memoizing everywhere.",
    coding: builders.coding(T, "When is useCallback useful for child components?", "When child is memoized and receives stable callback reference.", "Avoid premature optimization.", "", "—", "—"),
  },
  {
    name: "error boundaries",
    beginner: "Class components catch render errors in children.",
    intermediate: "Fallback UI and logging to monitoring.",
    advanced: "Does not catch event handler errors — use try/catch.",
    scenario: builders.scenario(T, "errors", "White screen after deploy.", "Check error boundary, source maps, chunk load failure.", "Production monitoring."),
  },
  {
    name: "custom hooks",
    beginner: "Extract reusable stateful logic into useX hooks.",
    intermediate: "Hooks compose; follow rules of hooks.",
    advanced: "Share data fetching hooks with suspense integrations.",
    why: "Clean architecture signal.",
  },
  {
    name: "Redux fundamentals",
    beginner: "Single store, actions describe events, reducers pure.",
    intermediate: "RTK simplifies slices and async thunks.",
    advanced: "Normalize entities; avoid massive global state.",
    why: "Many codebases still use Redux.",
  },
  {
    name: "testing React",
    beginner: "React Testing Library queries by role/label.",
    intermediate: "Mock network with MSW; avoid testing implementation.",
    advanced: "Integration tests for critical flows.",
    bestPractice: { question: "What to test in a form component?", answer: "Submission outcomes, validation messages, accessibility.", explanation: "User-centric tests." },
  },
  {
    name: "accessibility (a11y)",
    beginner: "Semantic HTML, labels, keyboard focus.",
    intermediate: "ARIA only when semantics insufficient.",
    advanced: "Audit with axe; test tab order.",
    why: "Inclusive product quality.",
  },
  {
    name: "SSR and Next.js basics",
    beginner: "Server renders HTML; hydrates on client.",
    intermediate: "getServerSideProps/getStaticProps patterns in pages router.",
    advanced: "App router server components reduce client JS.",
    why: "Modern React jobs.",
  },
  {
    name: "security in React",
    beginner: "Sanitize HTML; never trust user input.",
    intermediate: "Avoid storing JWT in localStorage if XSS risk.",
    advanced: "CSP headers and dependency scanning.",
    scenario: builders.scenario(T, "security", "XSS via user bio field.", "Sanitize, encode, CSP, remove dangerouslySetInnerHTML.", "Defense in depth."),
  },
  {
    name: "lists and keys",
    beginner: "map() renders lists; key must be stable unique id.",
    intermediate: "Avoid index keys when list reorders.",
    advanced: "Virtualize long lists with react-window.",
    why: "Common bug source.",
  },
  {
    name: "suspense and lazy",
    beginner: "React.lazy code-splits components; Suspense shows fallback.",
    intermediate: "Route-based splitting reduces initial bundle.",
    advanced: "Data suspense with frameworks (Relay/Next).",
    why: "Performance patterns.",
  },
  {
    name: "state management choice",
    beginner: "Local state first; context for theme/auth.",
    intermediate: "Redux/Zustand for complex shared state.",
    advanced: "Match tool to team scale and devtools needs.",
    why: "System design for frontend.",
  },
  {
    name: "useRef",
    beginner: "useRef holds mutable value without re-render.",
    intermediate: "DOM refs for focus; store previous value.",
    advanced: "Avoid overusing refs to bypass React data flow.",
    why: "Hooks depth.",
  },
]);
