import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "Spring Boot";

export const springbootConcepts = buildTechConcepts(T, [
  {
    name: "Spring Boot auto-configuration",
    beginner: "@SpringBootApplication enables component scan + autoconfig.",
    intermediate: "Conditional beans via @ConditionalOnClass.",
    advanced: "Custom starters package reusable autoconfig.",
    mcq: builders.mcq(T, "boot", "Which file can exclude auto-config?", ["application.properties/yml", "pom only", "Dockerfile"], "application.properties/yml", "spring.autoconfigure.exclude."),
  },
  {
    name: "dependency injection",
    beginner: "@Autowired/@RequiredArgsConstructor inject beans.",
    intermediate: "Prefer constructor injection for testability.",
    advanced: "@Primary @Qualifier resolve conflicts.",
    why: "Core Spring interviews.",
  },
  {
    name: "REST controllers",
    beginner: "@RestController + @GetMapping/@PostMapping.",
    intermediate: "@Valid DTO validation; ResponseEntity status.",
    advanced: "Version APIs with headers or path.",
    coding: builders.coding(T, "Return 201 with Location header on create.", "ResponseEntity.created(uri).body(dto).", "REST best practice.", "", "—", "—"),
  },
  {
    name: "Spring Data JPA",
    beginner: "Repository interfaces derive queries.",
    intermediate: "@Query JPQL/native; pagination Pageable.",
    advanced: "N+1 problem — fetch join or @EntityGraph.",
    scenario: builders.scenario(T, "JPA", "List endpoint slow — 1000 queries.", "N+1: add join fetch or batch size.", "Classic ORM issue."),
  },
  {
    name: "transactions",
    beginner: "@Transactional on service layer.",
    intermediate: "Propagation REQUIRED vs REQUIRES_NEW.",
    advanced: "Self-invocation bypasses proxy — inject self carefully.",
    why: "Data integrity.",
  },
  {
    name: "Spring Security",
    beginner: "Filter chain; authenticate before authorize.",
    intermediate: "JWT Resource Server OAuth2.",
    advanced: "Method security @PreAuthorize.",
    scenario: builders.scenario(T, "security", "403 on valid JWT.", "Check roles, issuer, clock skew, CORS preflight.", "Debug filter order."),
  },
  {
    name: "exception handling",
    beginner: "@ControllerAdvice @ExceptionHandler global errors.",
    intermediate: "ProblemDetail RFC 7807 responses.",
    advanced: "Map domain exceptions to HTTP codes consistently.",
    why: "API quality.",
  },
  {
    name: "configuration profiles",
    beginner: "application-dev.yml vs prod profiles.",
    intermediate: "@Profile beans per environment.",
    advanced: "Externalize secrets via vault/parameter store.",
    why: "12-factor apps.",
  },
  {
    name: "Actuator and monitoring",
    beginner: "spring-boot-starter-actuator health endpoints.",
    intermediate: "Micrometer metrics Prometheus.",
    advanced: "Custom health indicators for dependencies.",
    why: "Production readiness.",
  },
  {
    name: "microservices",
    beginner: "Spring Cloud discovery config gateway.",
    intermediate: "Resilience4j circuit breaker retry.",
    advanced: "Saga/outbox for distributed transactions.",
    why: "Enterprise Java roles.",
  },
  {
    name: "testing",
    beginner: "@SpringBootTest integration context.",
    intermediate: "@WebMvcTest slices controllers.",
    advanced: "Testcontainers for real DB integration.",
    bestPractice: { question: "Unit vs integration in Spring?", answer: "Unit pure logic; slice/integration for wiring and HTTP.", explanation: "Test pyramid." },
  },
  {
    name: "caching",
    beginner: "@Cacheable on read-heavy methods.",
    intermediate: "Redis cache manager TTL.",
    advanced: "Cache eviction on writes @CacheEvict.",
    why: "Performance patterns.",
  },
  {
    name: "async and scheduling",
    beginner: "@Async runs method on thread pool.",
    intermediate: "@Scheduled cron jobs.",
    advanced: "Message-driven @KafkaListener.",
    why: "Background processing.",
  },
  {
    name: "validation",
    beginner: "Bean Validation @NotNull @Email on DTOs.",
    intermediate: "Groups for create vs update.",
    advanced: "Custom validators for business rules.",
    why: "Input safety.",
  },
  {
    name: "OpenAPI documentation",
    beginner: "springdoc-openapi exposes Swagger UI.",
    intermediate: "Annotate schemas for client codegen.",
    advanced: "Contract-first with consumers.",
    why: "API teams.",
  },
  {
    name: "deployment",
    beginner: "Executable jar java -jar.",
    intermediate: "Docker multi-stage builds.",
    advanced: "GraalVM native image trade-offs.",
    why: "DevOps integration.",
  },
  {
    name: "logging",
    beginner: "SLF4J with Logback defaults.",
    intermediate: "MDC trace id across requests.",
    advanced: "Structured logging JSON.",
    why: "Observability.",
  },
  {
    name: "migration Flyway/Liquibase",
    beginner: "Versioned SQL migrations on startup.",
    intermediate: "Never edit applied migrations.",
    advanced: "Rollback strategy and baselines.",
    why: "Schema evolution.",
  },
]);
