import { buildTechConcepts, builders } from "./topicBuilder.js";

const T = "SQL";

export const sqlConcepts = buildTechConcepts(T, [
  {
    name: "SELECT fundamentals",
    beginner: "SELECT columns FROM table WHERE condition; ORDER BY sorts.",
    intermediate: "DISTINCT removes duplicates; LIMIT paginates.",
    advanced: "Covering indexes avoid table lookups.",
    mcq: builders.mcq(T, "SELECT", "Which clause filters rows before grouping?", ["WHERE", "HAVING", "ORDER BY"], "WHERE", "HAVING filters groups after GROUP BY."),
    coding: builders.coding(T, "Write query: top 3 products by revenue in 2024.", "GROUP BY product, SUM revenue, ORDER BY desc LIMIT 3 WHERE year=2024.", "Mention index on (year, product).", "", "O(n log n) sort", "O(1)"),
  },
  {
    name: "JOINs",
    beginner: "INNER keeps matches; LEFT keeps all left rows.",
    intermediate: "Join on indexed keys; avoid Cartesian products.",
    advanced: "Choose join order; analyze EXPLAIN plan.",
    scenario: builders.scenario(T, "JOIN", "Report query suddenly slow after data growth.", "Check missing index on join keys; update statistics.", "EXPLAIN ANALYZE."),
  },
  {
    name: "normalization",
    beginner: "1NF atomic values; 2NF no partial dependency; 3NF no transitive.",
    intermediate: "Denormalize read-heavy reporting carefully.",
    advanced: "Star schema for warehouses vs OLTP 3NF.",
    why: "DB design interviews.",
  },
  {
    name: "indexes",
    beginner: "B-tree indexes speed lookups; cost on writes.",
    intermediate: "Composite index column order matters.",
    advanced: "Avoid functions on indexed columns in WHERE.",
    debug: builders.debug(T, "index", "Index exists but full table scan.", ["Function on column, wrong column order, low selectivity"], "Function on column, wrong column order, low selectivity", "Check predicate sargability."),
  },
  {
    name: "aggregations",
    beginner: "COUNT SUM AVG GROUP BY aggregate rows.",
    intermediate: "HAVING filters groups; WHERE filters rows first.",
    advanced: "ROLLUP/CUBE for reports.",
    why: "Analytics SQL.",
  },
  {
    name: "subqueries vs CTEs",
    beginner: "Subquery nested; CTE WITH clause readable.",
    intermediate: "CTEs can be recursive for hierarchies.",
    advanced: "Optimizer may materialize CTE — test plan.",
    why: "Complex query interviews.",
  },
  {
    name: "transactions ACID",
    beginner: "BEGIN COMMIT ROLLBACK; all or nothing.",
    intermediate: "Isolation levels prevent dirty reads.",
    advanced: "Deadlocks — retry with ordering locks.",
    scenario: builders.scenario(T, "transactions", "Transfer money between accounts safely.", "Transaction with row locks; check balance constraints.", "Atomicity."),
  },
  {
    name: "window functions",
    beginner: "OVER PARTITION BY with ROW_NUMBER RANK.",
    intermediate: "Running totals with SUM OVER ORDER BY.",
    advanced: "Frames ROWS BETWEEN for moving averages.",
    coding: builders.coding(T, "Find second highest salary per department.", "DENSE_RANK or ROW_NUMBER partitioned by dept.", "Handle ties explicitly.", "", "O(n log n)", "O(n)"),
  },
  {
    name: "constraints",
    beginner: "PRIMARY KEY, FOREIGN KEY, UNIQUE, NOT NULL.",
    intermediate: "ON DELETE CASCADE vs RESTRICT.",
    advanced: "Check constraints validate domain rules.",
    why: "Data integrity.",
  },
  {
    name: "query optimization",
    beginner: "EXPLAIN shows plan; look for scans.",
    intermediate: "Select only needed columns; avoid SELECT *.",
    advanced: "Partition large tables; archive cold data.",
    why: "Production DBA topics.",
  },
  {
    name: "NULL handling",
    beginner: "NULL unknown; use IS NULL not = NULL.",
    intermediate: "COALESCE defaults; COUNT(*) vs COUNT(col).",
    advanced: "Three-valued logic in filters.",
    output: builders.output(T, "SELECT NULL = NULL returns?", "UNKNOWN/NULL in SQL", ["TRUE", "FALSE", "NULL/UNKNOWN"], "NULL/UNKNOWN", "SQL three-valued logic."),
  },
  {
    name: "views and stored procedures",
    beginner: "Views saved queries; procedures compiled on server.",
    intermediate: "Materialized views for speed.",
    advanced: "Security via views limiting columns.",
    why: "Enterprise databases.",
  },
  {
    name: "NoSQL comparison",
    beginner: "SQL relational schema; NoSQL flexible models.",
    intermediate: "Choose SQL when transactions/joins critical.",
    advanced: "Polyglot persistence in microservices.",
    why: "Architecture trade-offs.",
  },
  {
    name: "SQL injection",
    beginner: "Never concatenate user input into SQL.",
    intermediate: "Parameterized queries/prepared statements.",
    advanced: "Least privilege DB users.",
    scenario: builders.scenario(T, "security", "Login bypass with ' OR 1=1 --", "Use prepared statements; input validation.", "Classic injection."),
  },
  {
    name: "reporting queries",
    beginner: "Date filters with ranges sargable.",
    intermediate: "Pre-aggregate nightly for dashboards.",
    advanced: "Columnstore for analytics workloads.",
    why: "BI engineer path.",
  },
  {
    name: "foreign keys and relations",
    beginner: "FK enforces referential integrity.",
    intermediate: "Many-to-many via junction table.",
    advanced: "Indexing FK columns on child tables.",
    why: "Schema design.",
  },
  {
    name: "UPSERT patterns",
    beginner: "INSERT ... ON CONFLICT DO UPDATE in PostgreSQL.",
    intermediate: "MERGE in SQL Server/Oracle variants.",
    advanced: "Idempotent ingestion pipelines.",
    why: "Data engineering.",
  },
  {
    name: "execution plans",
    beginner: "Rows estimate vs actual indicate issues.",
    intermediate: "Update stats; avoid implicit conversions.",
    advanced: "Hint only as last resort.",
    bestPractice: { question: "First step when query regresses?", answer: "Compare EXPLAIN before/after; check indexes and stats.", explanation: "Evidence-based tuning." },
  },
]);
